# Generated by Django 5.0 on 2023-12-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1996-02-01'),
            preserve_default=False,
        ),
    ]
