# Generated by Django 5.0.2 on 2024-02-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='places',
            new_name='tplaces',
        ),
    ]
